spring:
  datasource:
    username: root
    password: 1234rewQ!@
    url: jdbc:mysql://localhost:3306/ticketgenerator?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&jdbcCompliantTruncation=false
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

ticket:
  sequence:
    bunch: 4
    init: 15
    end: 30


